//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorldEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWorldEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _112_ArrowCurve_Blue_Left_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowCurve_Blue_Left_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_ArrowCurve_Blue_Right_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowCurve_Blue_Right_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _112_ArrowReturnLeft_Blue {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowReturnLeft_Blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_ArrowReturnLeft_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowReturnLeft_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _112_ArrowReturnRight_Blue {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowReturnRight_Blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_ArrowReturnRight_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_ArrowReturnRight_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowLong_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowLong_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowLong_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowLong_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowLong_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowLong_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowLong_Orange_64x64_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowLong_Orange_64x64_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowShort_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowShort_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowShort_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowShort_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowShort_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowShort_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_DownArrowShort_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowShort_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowLong_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowLong_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowLong_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowLong_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowLong_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowLong_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowShort_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowShort_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowShort_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowShort_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowShort_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowShort_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_LeftArrowShort_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowShort_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Minus_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Minus_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Minus_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Minus_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Minus_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Minus_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Minus_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Minus_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Plus_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Plus_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Plus_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Plus_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Plus_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Plus_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_Plus_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Plus_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _112_RefreshArrow_Blue {
            get {
                object obj = ResourceManager.GetObject("_112_RefreshArrow_Blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RefreshArrow_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RefreshArrow_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowLong_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowLong_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowLong_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowLong_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowLong_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowLong_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowLong_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowLong_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowShort_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowShort_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowShort_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowShort_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowShort_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowShort_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_RightArrowShort_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowShort_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowLong_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowLong_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowLong_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowLong_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowLong_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowLong_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowLong_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowLong_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowShort_Blue_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowShort_Blue_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowShort_Green_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowShort_Green_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowShort_Grey_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowShort_Grey_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _112_UpArrowShort_Orange_48x48_72 {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowShort_Orange_48x48_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1447_eraser_256x256 {
            get {
                object obj = ResourceManager.GetObject("_1447_eraser_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1447_eraser_48x48 {
            get {
                object obj = ResourceManager.GetObject("_1447_eraser_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyHL {
            get {
                object obj = ResourceManager.GetObject("CopyHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutHL {
            get {
                object obj = ResourceManager.GetObject("CutHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_redoHL {
            get {
                object obj = ResourceManager.GetObject("Edit_redoHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_UndoHL {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_pointer {
            get {
                object obj = ResourceManager.GetObject("move_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Perspective_view {
            get {
                object obj = ResourceManager.GetObject("Perspective_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon RedoIco {
            get {
                object obj = ResourceManager.GetObject("RedoIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon RefreshIco {
            get {
                object obj = ResourceManager.GetObject("RefreshIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rotate_pointer {
            get {
                object obj = ResourceManager.GetObject("rotate_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveHL {
            get {
                object obj = ResourceManager.GetObject("SaveHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scale_pointer {
            get {
                object obj = ResourceManager.GetObject("scale_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap solid_mod {
            get {
                object obj = ResourceManager.GetObject("solid_mod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon UndoIco {
            get {
                object obj = ResourceManager.GetObject("UndoIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wireframe {
            get {
                object obj = ResourceManager.GetObject("wireframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
