//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsec.Configuration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parsec Configuration")]
        public string WindowHeader {
            get {
                return ((string)(this["WindowHeader"]));
            }
            set {
                this["WindowHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("< &Back")]
        public string BackBtnText {
            get {
                return ((string)(this["BackBtnText"]));
            }
            set {
                this["BackBtnText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Next >")]
        public string NextBtnText {
            get {
                return ((string)(this["NextBtnText"]));
            }
            set {
                this["NextBtnText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cancel")]
        public string CancelBtnText {
            get {
                return ((string)(this["CancelBtnText"]));
            }
            set {
                this["CancelBtnText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I agree")]
        public string DescriptionAgreeText {
            get {
                return ((string)(this["DescriptionAgreeText"]));
            }
            set {
                this["DescriptionAgreeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description")]
        public string DescriptionTab_Description {
            get {
                return ((string)(this["DescriptionTab_Description"]));
            }
            set {
                this["DescriptionTab_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parsec Configuration")]
        public string DescriptionTab_Tile {
            get {
                return ((string)(this["DescriptionTab_Tile"]));
            }
            set {
                this["DescriptionTab_Tile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to Parsec Configuration Wizard")]
        public string IntroTab_Title {
            get {
                return ((string)(this["IntroTab_Title"]));
            }
            set {
                this["IntroTab_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This wizard will gather all")]
        public string IntroTab_Text {
            get {
                return ((string)(this["IntroTab_Text"]));
            }
            set {
                this["IntroTab_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 460")]
        public global::System.Drawing.Size FixedSize {
            get {
                return ((global::System.Drawing.Size)(this["FixedSize"]));
            }
            set {
                this["FixedSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description")]
        public string ProcessTabDescription {
            get {
                return ((string)(this["ProcessTabDescription"]));
            }
            set {
                this["ProcessTabDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string ProcessTabTitle {
            get {
                return ((string)(this["ProcessTabTitle"]));
            }
            set {
                this["ProcessTabTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string SendTabTitle {
            get {
                return ((string)(this["SendTabTitle"]));
            }
            set {
                this["SendTabTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Description")]
        public string SendTabDescription {
            get {
                return ((string)(this["SendTabDescription"]));
            }
            set {
                this["SendTabDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for wating.")]
        public string FinishTabText {
            get {
                return ((string)(this["FinishTabText"]));
            }
            set {
                this["FinishTabText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finishing Wizard work.")]
        public string FinishTabTitle {
            get {
                return ((string)(this["FinishTabTitle"]));
            }
            set {
                this["FinishTabTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Prepearing")]
        public string Progress_prepearing {
            get {
                return ((string)(this["Progress_prepearing"]));
            }
            set {
                this["Progress_prepearing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saving")]
        public string Progress_Saving {
            get {
                return ((string)(this["Progress_Saving"]));
            }
            set {
                this["Progress_Saving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Getting info about your FireWall")]
        public string Progress_FireWal {
            get {
                return ((string)(this["Progress_FireWal"]));
            }
            set {
                this["Progress_FireWal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Getting info about Services")]
        public string Progress_Services {
            get {
                return ((string)(this["Progress_Services"]));
            }
            set {
                this["Progress_Services"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Getting info about your Domain")]
        public string Progress_Domain {
            get {
                return ((string)(this["Progress_Domain"]));
            }
            set {
                this["Progress_Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Getting info about DHCP")]
        public string Progress_DHCP {
            get {
                return ((string)(this["Progress_DHCP"]));
            }
            set {
                this["Progress_DHCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sucesfully saved")]
        public string Progress_Saved {
            get {
                return ((string)(this["Progress_Saved"]));
            }
            set {
                this["Progress_Saved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("does not saved, error!")]
        public string Progress_SaveError {
            get {
                return ((string)(this["Progress_SaveError"]));
            }
            set {
                this["Progress_SaveError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Getting info about your Registry")]
        public string Progress_Registry {
            get {
                return ((string)(this["Progress_Registry"]));
            }
            set {
                this["Progress_Registry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Programm have been done sucesfully")]
        public string Progress_done {
            get {
                return ((string)(this["Progress_done"]));
            }
            set {
                this["Progress_done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Programm have been done with errors.")]
        public string Progress_doneWithError {
            get {
                return ((string)(this["Progress_doneWithError"]));
            }
            set {
                this["Progress_doneWithError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tracing Install Path")]
        public string Progress_folderTrace {
            get {
                return ((string)(this["Progress_folderTrace"]));
            }
            set {
                this["Progress_folderTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CreatingNameMode {
            get {
                return ((int)(this["CreatingNameMode"]));
            }
            set {
                this["CreatingNameMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFolderTraceInWindow {
            get {
                return ((bool)(this["ShowFolderTraceInWindow"]));
            }
            set {
                this["ShowFolderTraceInWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open File to look it?")]
        public string openForWatch {
            get {
                return ((string)(this["openForWatch"]));
            }
            set {
                this["openForWatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open")]
        public string OpenFile {
            get {
                return ((string)(this["OpenFile"]));
            }
            set {
                this["OpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to open file")]
        public string FileOpenEror {
            get {
                return ((string)(this["FileOpenEror"]));
            }
            set {
                this["FileOpenEror"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Saving error")]
        public string SavinError {
            get {
                return ((string)(this["SavinError"]));
            }
            set {
                this["SavinError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sending Error")]
        public string MailSendingError {
            get {
                return ((string)(this["MailSendingError"]));
            }
            set {
                this["MailSendingError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\MDO\\ParsecNET 3")]
        public string RegistryKeyLoc {
            get {
                return ((string)(this["RegistryKeyLoc"]));
            }
            set {
                this["RegistryKeyLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallPath")]
        public string RegistryKeyValue {
            get {
                return ((string)(this["RegistryKeyValue"]));
            }
            set {
                this["RegistryKeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please, send gathered information to us via e-mail.")]
        public string MailTabText {
            get {
                return ((string)(this["MailTabText"]));
            }
            set {
                this["MailTabText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Send via E-Mail (Recomendet)")]
        public string MilSendRBText {
            get {
                return ((string)(this["MilSendRBText"]));
            }
            set {
                this["MilSendRBText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save local (Optional)")]
        public string SaveRarRT {
            get {
                return ((string)(this["SaveRarRT"]));
            }
            set {
                this["SaveRarRT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Use it if you have no configurated mail client on this computer or it doesn\'t sup" +
            "port MAPI.")]
        public string Use {
            get {
                return ((string)(this["Use"]));
            }
            set {
                this["Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reports@mdo.ru")]
        public string mailtoLink {
            get {
                return ((string)(this["mailtoLink"]));
            }
            set {
                this["mailtoLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Parsec_Report]")]
        public string MailSubject {
            get {
                return ((string)(this["MailSubject"]));
            }
            set {
                this["MailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OS info")]
        public string Progress_OSInfo {
            get {
                return ((string)(this["Progress_OSInfo"]));
            }
            set {
                this["Progress_OSInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>OK</string>\r\n  <string>User aborted, are u sure?\nMay be you have misclicke" +
            "d, resend?</string>\r\n  <string>General MAPI failure \nError code 2</string>\r\n  <s" +
            "tring>MAPI login failure\nError code 3</string>\r\n  <string>Disk full \nError code " +
            "4</string>\r\n  <string>Insufficient memory \nError code 5</string>\r\n  <string>Acce" +
            "ss denied \nError code 6</string>\r\n  <string>Unknown Error\nError code 7</string>\r" +
            "\n  <string>Too many sessions\nError code 8</string>\r\n  <string>Too many files wer" +
            "e specified \nError code 9</string>\r\n  <string>Too many recipients were specified" +
            " \nError code 10</string>\r\n  <string>A specified attachment was not found \nError " +
            "code 11</string>\r\n  <string>Attachment open failure \nError code 12</string>\r\n  <" +
            "string>Attachment write failure \nError code 13</string>\r\n  <string>Unknown recip" +
            "ient \nError code 14</string>\r\n  <string>Bad recipient type \nError code 15</strin" +
            "g>\r\n  <string>No messages\nError code 16</string>\r\n  <string>Invalid message \nErr" +
            "or code 17</string>\r\n  <string>Text too large \nError code 18</string>\r\n  <string" +
            ">Invalid session \nError code 19</string>\r\n  <string>Type not supported \nError co" +
            "de 20</string>\r\n  <string>A recipient was specified ambiguously \nError code 21</" +
            "string>\r\n  <string>Message in use \nError code 22</string>\r\n  <string>Network fai" +
            "lure \nError code 23</string>\r\n  <string>Invalid edit fields \nError code 24</stri" +
            "ng>\r\n  <string>Invalid recipients \nError code 25</string>\r\n  <string>Not support" +
            "ed \nError code 26 </string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MailErrors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MailErrors"]));
            }
            set {
                this["MailErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parsec.Config report arhive in attachments.")]
        public string MailBody {
            get {
                return ((string)(this["MailBody"]));
            }
            set {
                this["MailBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Now this wizar will find info anout:\n-OS Version\n-FireWall\n-Domain\n-DHCP\n-Event l" +
            "ogs\n-Parsec Configs\n-Parsec Logs\n-Registry Keys")]
        public string DescriptionFullText {
            get {
                return ((string)(this["DescriptionFullText"]));
            }
            set {
                this["DescriptionFullText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MDO%20<reports@mdo.ru>")]
        public string MailAdr {
            get {
                return ((string)(this["MailAdr"]));
            }
            set {
                this["MailAdr"] = value;
            }
        }
    }
}
